### ISSUE TITLE
.NET Standard version

### ISSUE THREAD

**Issue by gijsmater** [paynl/sdk-net#1]
At this moment I am migrating my PAY implementation from V2 to V3. I use this in .NET Framework and .NET Core applications.

I would love to use this NuGet Package but the .NET Standard version is 2.1. Version 2.1. has incompatible with .NET Framework. For me usually the reason for using .NET Standard is so I can use the project in .NET Framework and .NET Core. 

.NET Standard version compatibilities:
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

Why did you made the choice to use 2.1 and not 2.0? Is there any chance of changing it to 2.0?

**Comment by NickHes** [comment]
Hi @gijsmater, given that our legacy .NET SDK does not support V3 we agree with the rationale you provide. We are currently looking to downgrade the API version to 2.0 and you can expect a package update shortly.
