### ISSUE TITLE
Order Customer date of birth has incorrect property name and should be nullable

### ISSUE THREAD

**Issue by gijsmater** [paynl/sdk-net#11]
In the following class `PAYNLSDK.SDK/V3/DataTransferObjects/Orders/V3Customer.cs` there is a property now called `dateOfBirth`.
This property name is incorrect and the type should be a nullable DateTime, as seen in the API documentation (https://developer.pay.nl/reference/api_create_order).

With the current name PAY will just ignore it.

My suggested change would be:
```
[JsonPropertyName("birthDate")]
public DateTime? DateOfBirth { get; set; }
```

![image](https://github.com/user-attachments/assets/ac6576ac-c1df-4e01-9725-7e2064064c9f)

**Comment by Joep-Scenius** [comment]
Hi Gijs,

Thank you for your report, this will be addressed and a update will be released in the near future
